# Generated by Django 4.1 on 2022-08-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_topic_date_added_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='text1',
            new_name='text',
        ),
    ]
