# Generated by Django 4.1 on 2022-08-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_text1_description_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='text',
            new_name='text1',
        ),
    ]
