# Generated by Django 4.1 on 2022-08-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_text_description_text1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='text1',
            new_name='text',
        ),
    ]
